--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FrozenArea/BackgroundMusic
build-by-default: true
branches:
- master
projects:
  BackgroundMusic:
    path: ""
    libs:
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.1.7
...
