---
name: BackgroundMusic
author: NhanAZ
version: 0.0.3
api: 5.0.0
main: NhanAZ\BackgroundMusic\Main
website: https://github.com/NhanAZ
description: Background music will be played many times when players join the server
...
